ui: tape
browsers:
  - name: chrome
    version: 36..latest
  - name: firefox
    version: 25..latest
  - name: safari
    version: 5..latest
  - name: ie
    version: 6..latest
  - name: opera
    version: 11..latest
  - name: iphone
<<<<<<< HEAD
    version: [4.3..7.0, 8.0..latest]
=======
    version: 4.3..latest
>>>>>>> parent of 563c219... fix zuul.yml, iPhone 7.1 failing
  - name: ipad
    version: 4.3..latest
  - name: android
    version: 4.0..latest
